[project]
name = "habit-tracker-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "davidanukam", email = "davidanukam72@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
habit-tracker-api = "habit_tracker_api:main"

[tool.fastapi]
entrypoint = "src.habit_tracker_api.main:app"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
