[project]
name = "habit-tracker-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "davidanukam", email = "davidanukam72@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.62.0",
]

[project.scripts]
dev = "start_dev:main"
habit-tracker-api = "main:main"
gui = "frontend.run_gui:main"

[tool.fastapi]
entrypoint = "backend.api:app"

# Tell setuptools (default builder) to find modules directly under src/
[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["honcho>=2.0.0"]
